services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${BOOKY_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${BOOKY_DATABASE_USER}
      POSTGRES_PASSWORD: ${BOOKY_DATABASE_PASSWORD}
      POSTGRES_DB: ${BOOKY_DATABASE_NAME}

  sonarqube:
    image: sonarqube:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_HOST: "0.0.0.0"
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${BOOKY_DATABASE_NAME}
      SONAR_JDBC_USERNAME: ${BOOKY_DATABASE_USER}
      SONAR_JDBC_PASSWORD: ${BOOKY_DATABASE_PASSWORD}
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: